### PR TITLE
Fix choose_backend() logic

### PR DESCRIPTION
**Pull request by cpq**
Also factor log writing into a separate function.

[Review on Reviewable](https://reviewable.io/reviews/cesanta/fossa/279)

### CODE REVIEW

**Comment by gelraen** [comment]
<sup>**[apps/load_balancer/load_balancer.c, line 104 \[r2\]](https://reviewable.io:443/reviews/cesanta/fossa/279#-Jn0J5xpP4jmrHhHU_V8)** ([raw file](https://github.com/cesanta/fossa/blob/bbc8af5db86f3f45ca5aede81decd2ee9b92082f/apps/load_balancer/load_balancer.c#L104)):</sup>
This can cause it to not switch to a backend with more specific prefix if its usage counter is higher.

```
      if (has_prefix(&hm.uri, s_http_backends[i].uri_prefix) &&
          matches_vhost(&vhost, s_http_backends[i].vhost) &&
          (chosen == -1 ||
           /* Use most specific URI prefix. */
           strlen(s_http_backends[i].uri_prefix) >
               strlen(s_http_backends[chosen].uri_prefix) ||
          /* Among prefixes of the same length chose the least used. */
          (strlen(s_http_backends[i].uri_prefix) =
               strlen(s_http_backends[chosen].uri_prefix) &&
           s_http_backends[i].usage_counter <
               s_http_backends[chosen].usage_counter)))
```

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/279)

**Comment by cpq** [comment]
<sup>**[apps/load_balancer/load_balancer.c, line 104 \[r2\]](https://reviewable.io:443/reviews/cesanta/fossa/279#-Jn0J5xpP4jmrHhHU_V8)** ([raw file](https://github.com/cesanta/fossa/blob/bbc8af5db86f3f45ca5aede81decd2ee9b92082f/apps/load_balancer/load_balancer.c#L104)):</sup>
Great catch. Done

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/279)

**Comment by gelraen** [comment]
LGTM

---

Reviewed files:
- apps/load_balancer/load_balancer.c @ r3
- apps/load_balancer/Makefile @ r2
- platforms/arduino_wifi_CC3000/avrsupport.cpp @ r2
- platforms/arduino_wifi_CC3000/avrsupport.h @ r2

---

<sup>**[platforms/arduino_wifi_CC3000/avrsupport.h, line 47 \[r3\]](https://reviewable.io:443/reviews/cesanta/fossa/279#-Jn0QBhyZKCFqs8fFVJo)** ([raw file](https://github.com/cesanta/fossa/blob/a760b558de2fb268cc8fc77449b5320aee40b912/platforms/arduino_wifi_CC3000/avrsupport.h#L47)):</sup>
Maybe add a newline to make clang-format happy?

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/279)

**Comment by cpq** [comment]
<sup>**[platforms/arduino_wifi_CC3000/avrsupport.h, line 47 \[r3\]](https://reviewable.io:443/reviews/cesanta/fossa/279#-Jn0QBhyZKCFqs8fFVJo)** ([raw file](https://github.com/cesanta/fossa/blob/a760b558de2fb268cc8fc77449b5320aee40b912/platforms/arduino_wifi_CC3000/avrsupport.h#L47)):</sup>
Done.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/279)

**Pull request merged**
