### PR TITLE
Add Range: header support (#237)

### PR DESCRIPTION
**Pull request by cpq**
DIFFTEST=246
Refactored unit test a little, and done some yak shaving.

[Review on Reviewable](https://reviewable.io/reviews/cesanta/fossa/247)

### CODE REVIEW

**Comment by alashkin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/247)

Reviewed files:
- examples/restful_server/restful_server.c @ r1
- fossa.c @ r1
- fossa.h @ r1





---

<sup>**[README.md, line 9 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/247#-JlWacowLG1-O71rov0I)** ([raw file](https://github.com/cesanta/fossa/blob/6800cba78f29a3559fc005242bf0e0153d9abeac/README.md#L9)):</sup>
Should we use 'Fossa' as a link?

`multi-protocol networking library` looks like link to Wikipedia's page with networking library description.

It's small thing, I know.

---

**Comment by alashkin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/247)

Reviewed files:
- src/common.h @ r1
- test/data/range.txt @ r1





---

<sup>**[test/data/range.txt, line 9 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/247#-JlWgfoHY38MjpIAifgm)** ([raw file](https://github.com/cesanta/fossa/blob/6800cba78f29a3559fc005242bf0e0153d9abeac/test/data/range.txt#L9)):</sup>
Thanks to this abnormal hope of theirs, a singular and very curious
disease, with the property of evolving, arose and exists among them even
until now—a disease called 'tomorrow.' 

---

**Comment by alashkin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/247)

Reviewed files:
- README.md @ r1
- src/http.c @ r1
- src/http.h @ r1
- src/util.c @ r1
- src/util.h @ r1
- test/data/rewrites/foo.com/index.html @ r1
- test/data/rewrites/msg.txt @ r1
- test/unit_test.c @ r1

---

LGTM,
2 little questions, fell free to merge if question #2 is OK

---

<sup>**[src/http.c, line 448 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/247#-JlWhXfO3DqhD6q8D-Hv)** ([raw file](https://github.com/cesanta/fossa/blob/6800cba78f29a3559fc005242bf0e0153d9abeac/src/http.c#L448)):</sup>
if `sizeof(buf)` ALWAYS bigger than `io->len`?

---

**Comment by alashkin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/247)







---

<sup>**[fossa.c, line 2646 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/247#-JlWmrNbxj-G5isAikDl)** ([raw file](https://github.com/cesanta/fossa/blob/6800cba78f29a3559fc005242bf0e0153d9abeac/fossa.c#L2646)):</sup>
Is ns_send_http_file visible to end-user?
What if user calls `ns_send_http_file` twice: first with correct (but big) file, and second - with wrong file. Then it gonna a memory leak.
If second file is correct as well it looks like we will lose previous one.

---

**Comment by cpq** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/247)







---

<sup>**[fossa.c, line 2646 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/247#-JlWmrNbxj-G5isAikDl)** ([raw file](https://github.com/cesanta/fossa/blob/6800cba78f29a3559fc005242bf0e0153d9abeac/fossa.c#L2646)):</sup>
Good catch.
`ns_send_http_file` is not visible to the user, but we might consider making it visible. I'll add a guard in the other PR when I fix a leak with proto_data.

---

<sup>**[README.md, line 9 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/247#-JlWacowLG1-O71rov0I)** ([raw file](https://github.com/cesanta/fossa/blob/6800cba78f29a3559fc005242bf0e0153d9abeac/README.md#L9)):</sup>
Done.

---

<sup>**[src/http.c, line 448 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/247#-JlWhXfO3DqhD6q8D-Hv)** ([raw file](https://github.com/cesanta/fossa/blob/6800cba78f29a3559fc005242bf0e0153d9abeac/src/http.c#L448)):</sup>
Very good catch.

io->len can be larger, which will overflow to_read to very large number, and a conditional below to_read > (size_t) left will be true, to_read will be set to left (potentially big) and fread() can overflow buf.

Fixed.

---

<sup>**[test/data/range.txt, line 9 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/247#-JlWgfoHY38MjpIAifgm)** ([raw file](https://github.com/cesanta/fossa/blob/6800cba78f29a3559fc005242bf0e0153d9abeac/test/data/range.txt#L9)):</sup>
Very good, very good :-)

---

**Comment by cpq** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/247)







---

**Comment by alashkin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/247)

Reviewed files:
- README.md @ r2
- src/http.c @ r2





---

<sup>**[README.md, line 7 \[r2\]](https://reviewable.io:443/reviews/cesanta/fossa/247#-JlZOlUvdgHg1C-alXbE)** ([raw file](https://github.com/cesanta/fossa/blob/5c977a04b85b3367267a8b56bd2876a7736f92be/README.md#L7)):</sup>
I'm looking here: https://github.com/cesanta/fossa/tree/range
And now  there's not link at all.
Could be it's because of `((`?

---

**Comment by alashkin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/247)

Reviewed files:
- fossa.c @ r2





---

**Comment by cpq** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/247)







---

<sup>**[README.md, line 8 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/247#-JlX1VoK6BC8PY149jPD)** ([raw file](https://github.com/cesanta/fossa/blob/6800cba78f29a3559fc005242bf0e0153d9abeac/README.md#L8)):</sup>
Yes, extra paren.
Fixed.

---

**Comment by alashkin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/247)

Reviewed files:
- README.md @ r3





---

**Pull request merged**
