### PR TITLE
Trim leading spaces in CGI interpreter

### PR DESCRIPTION
**Pull request by cpq**
Addresses https://github.com/cesanta/mongoose/issues/489

[Review on Reviewable](https://reviewable.io/reviews/cesanta/fossa/259)

### CODE REVIEW

**Comment by cpq** [comment]
I don't know why my clang-format removes spaces.

```
$ clang-format -version
clang-format version 3.6.0 (tags/google/testing/2015-01-13)
```

**Comment by gelraen** [comment]
Had the same issue with `clang-format` from Homebrew. `brew uninstall clang-format && brew install llvm36` fixed that for me.

---



---



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/259)

**Comment by mmikulicic** [comment]
I think @gelraen  had that version and reported that there was something bad.

`brew install llvm36`

**Comment by mmikulicic** [comment]
Ooop, I wanted to cancel the post after I noticed that @gelraen answered but it was "close and comment". Very nice UX have it grey...

**Comment by gelraen** [comment]
Reviewed files:
- fossa.c @ r1
- src/http.c @ r1

---



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/259)

**Comment by cpq** [comment]
reinstalled clang-format as suggested - thanks gents! ptal

---



---



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/259)

**Comment by cpq** [comment]
Reviewed files:
- fossa.c @ r1
- src/http.c @ r1

---



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/259)

**Comment by mmikulicic** [comment]
LGTM.

I'm afraid you have to create a new PR :-(

---



---



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/259)

**Comment by gelraen** [comment]
I'll just fix formatting in master directly.

**Pull request merged**
