### PR TITLE
Format 'apps' too and reformat everything

### PR DESCRIPTION
**Pull request by gelraen**
[Review on Reviewable](https://reviewable.io/reviews/cesanta/fossa/267)

### CODE REVIEW

**Comment by alashkin** [comment]
Could we exclude these files from commit:
```
M platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/cc3000_common.cpp (2)
M platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/cc3000_common.h (4)
M platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/evnt_handler.cpp (4)
M platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/hci.cpp (2)
M platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/hci.h (2)
M platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/netapp.cpp (2)
M platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/netapp.h (2)
M platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/sntp.cpp (38)
M platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/wlan.cpp (8)
M platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/wlan.h (2)
```
It is an external library.

**Comment by alashkin** [comment]
---

<sup>**[platforms/arduino_ethernet_W5100/avrsupport.cpp, line 28 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/267#-JmP5SiPbQ4vZtABIdsk)** ([raw file](https://github.com/cesanta/fossa/blob/e88727294aff654b84c2f0f026f2700189106380/platforms/arduino_ethernet_W5100/avrsupport.cpp#L28)):</sup>
Looks like it's wrong change?
it should be `extern void *__brkval;` (as it was)
Or, I again miss something?

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/267)

**Comment by gelraen** [comment]
Done.

---



---

<sup>**[platforms/arduino_ethernet_W5100/avrsupport.cpp, line 28 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/267#-JmP5SiPbQ4vZtABIdsk)** ([raw file](https://github.com/cesanta/fossa/blob/e88727294aff654b84c2f0f026f2700189106380/platforms/arduino_ethernet_W5100/avrsupport.cpp#L28)):</sup>
That's what `clang-format` did. Config file looks identical to the one in v7 for example. Is it producing a different output for you?

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/267)

**Comment by alashkin** [comment]
---

<sup>**[platforms/arduino_ethernet_W5100/avrsupport.cpp, line 28 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/267#-JmP5SiPbQ4vZtABIdsk)** ([raw file](https://github.com/cesanta/fossa/blob/e88727294aff654b84c2f0f026f2700189106380/platforms/arduino_ethernet_W5100/avrsupport.cpp#L28)):</sup>
We tried to maintain style manually, but now clang-format in change.
So - OK.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/267)

**Pull request merged**
