### PR TITLE
Amalgamate fossa.c

### PR DESCRIPTION
**Pull request by alashkin**
Amalgamate fossa.c after PR #202

### CODE REVIEW

**Comment by mmikulicic** [comment]
Out of curiosity, what happened ?

**Comment by alashkin** [comment]
It is a bit strange and I still investigate this.
I commented out one of internal include (net_internal.h - in net.c)
and use `git update-index --assume-unchanged src/net.c` coz I didn't want to commit this.
So, fossa.c contained line `/* #include "net_internal.h" */`
That is diagnosis.
`git diff` have said:
```
diff --git a/fossa.c b/fossa.c
index 6a095b6..f3c5048 100644
Binary files a/fossa.c and b/fossa.c differ
```
Files is different, but there is not differences =)
`git status` showed "no changes"

I've deleted (from disk) fossa.c & h, generated new, forces push - and - it works.

**Comment by alashkin** [comment]
I think I have to throw out my own fork and use Cesanta's repo in order to see these things _before_ merging.

**Comment by mmikulicic** [comment]
Yes, please work on a branch of the main repo so that circleci will kick in

**Pull request merged**
