### PR TITLE
Refactoring conditional directives.

### PR DESCRIPTION
**Pull request by wmarquesr**
A suggestion to compile entire statements and expressions, as suggested by code style guidelines from the Linux Kernel and practitioners.
- [Linux kernel coding style](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/CodingStyle#n892)
- [Living in the #ifdef Hell](https://www.cqse.eu/en/blog/living-in-the-ifdef-hell/)

It might improve code understanding, maintainability and error-proneness.

[Review on Reviewable](https://reviewable.io/reviews/cesanta/fossa/312)

### CODE REVIEW

**Comment by cpq** [comment]
Thank you.
Just to note, fossa has been migrated to mongoose, as it spelled on the project page.
I suggest to switch to mongoose - https://github.com/cesanta/mongoose

**Comment by wmarquesr** [comment]
Thanks.

**Comment by RomeroMalaquias** [comment]
Hello @cpq  i'm from the same research team of wmarquesr and i need to ask if you prefer this code before or after the commit. What do you think about this kind of change? 
Thanks in advance.

**Comment by cpq** [comment]
Thanks @RomeroMalaquias - feel free to send a PR against cesanta/mongoose.
Please sign the  https://docs.cesanta.com/contributors_la.shtml if you want your code be integrated.

**Pull request closed without merging**
