### PR TITLE
Add SSI support

### PR DESCRIPTION
**Pull request by cpq**
DIFFBASE=242

[Review on Reviewable](https://reviewable.io/reviews/cesanta/fossa/243)

### CODE REVIEW

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/243)

Reviewed files:
- fossa.c @ r1
- fossa.h @ r1
- src/common.h @ r1
- src/http.c @ r1
- src/http.h @ r1
- test/data/ssi/f1.txt @ r1
- test/data/ssi/index.shtml @ r1
- test/data/ssi/nested.shtml @ r1
- test/unit_test.c @ r1





---

<sup>**[src/http.c, line 568 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/243#-JlFIb0g1HOGzXvnnjxD)** ([raw file](https://github.com/cesanta/fossa/blob/0660863599cb337ce8fc8a197096a278ae71abfd/src/http.c#L568)):</sup>
what about `strlen(suffix) > strlen(str)` ?

If not, because checked somewhere else (it doesn't like though), what about declaring this precondition in the function's comment?

---

<sup>**[src/http.c, line 597 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/243#-JlFMCGxJdOAZCExOU-A)** ([raw file](https://github.com/cesanta/fossa/blob/0660863599cb337ce8fc8a197096a278ae71abfd/src/http.c#L597)):</sup>
should this `'/'` be `DIRSEP` ?

---

<sup>**[src/http.c, line 613 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/243#-JlFNRn0C5oRlUMdO3La)** ([raw file](https://github.com/cesanta/fossa/blob/0660863599cb337ce8fc8a197096a278ae71abfd/src/http.c#L613)):</sup>
(non actionable now)

At some point we should find a to log some stuff, in a way that is controllable by the user. This is a typical kind of errors you would like to see on your logs instead of showing it only to your customers.

---

<sup>**[src/http.c, line 675 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/243#-JlFOXLIz1xisODSgGwl)** ([raw file](https://github.com/cesanta/fossa/blob/0660863599cb337ce8fc8a197096a278ae71abfd/src/http.c#L675)):</sup>
according to some old mongoose documentation (http://linux.die.net/man/1/mongoose, http://mongoose.googlecode.com/svn/wiki/MongooseManual.wiki)) directives are silently ignored.

What's the rationale for the change in behaviour ?
Do we still maintain that kind of manual page for mongoose ?

---

<sup>**[src/http.c, line 732 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/243#-JlFPsnHrmx23MkLqfAj)** ([raw file](https://github.com/cesanta/fossa/blob/0660863599cb337ce8fc8a197096a278ae71abfd/src/http.c#L732)):</sup>
Here we have stub function in case ssi is disabled. In alternative we could have disabled the `else if(has_suffix(path, opts->ssi_suffix))` block below.

If I understood correctly, the difference is that any ssi_suffix match will now (silently) swallow the request, thus protecting the SSI source in case of serving by accident with a badly built fossa.

Should we do it less silently?

---

**Comment by cpq** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/243)







---

<sup>**[src/http.c, line 568 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/243#-JlFIb0g1HOGzXvnnjxD)** ([raw file](https://github.com/cesanta/fossa/blob/0660863599cb337ce8fc8a197096a278ae71abfd/src/http.c#L568)):</sup>
Done.

---

<sup>**[src/http.c, line 597 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/243#-JlFMCGxJdOAZCExOU-A)** ([raw file](https://github.com/cesanta/fossa/blob/0660863599cb337ce8fc8a197096a278ae71abfd/src/http.c#L597)):</sup>
I think regardless of DIRSEP, both slashes and backslashes should be stripped. E.g. windows runtime accepts both slash and backslash as dir separator

---

<sup>**[src/http.c, line 613 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/243#-JlFNRn0C5oRlUMdO3La)** ([raw file](https://github.com/cesanta/fossa/blob/0660863599cb337ce8fc8a197096a278ae71abfd/src/http.c#L613)):</sup>
Yeah

---

<sup>**[src/http.c, line 675 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/243#-JlFOXLIz1xisODSgGwl)** ([raw file](https://github.com/cesanta/fossa/blob/0660863599cb337ce8fc8a197096a278ae71abfd/src/http.c#L675)):</sup>
No we don't maintain the manual page.
I think it is worth alerting about unsupported SSI directive, wdyt?

---

<sup>**[src/http.c, line 732 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/243#-JlFPsnHrmx23MkLqfAj)** ([raw file](https://github.com/cesanta/fossa/blob/0660863599cb337ce8fc8a197096a278ae71abfd/src/http.c#L732)):</sup>
Yes, ssi files will be protected if ssi is not configured. Same goes for CGI (TBD). 
I've added send_http_error() call to the stub. 

---

**Comment by cpq** [comment]
PTAL.
Also fixed windows unit test build.

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/243)

Reviewed files:
- fossa.c @ r2
- fossa.h @ r2
- Makefile @ r2
- src/common.h @ r2
- src/http.c @ r2
- test/unit_test.c @ r2





---

<sup>**[src/http.c, line 597 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/243#-JlFMCGxJdOAZCExOU-A)** ([raw file](https://github.com/cesanta/fossa/blob/0660863599cb337ce8fc8a197096a278ae71abfd/src/http.c#L597)):</sup>
Then why don't you just write `"%s/%s"` instead of the extra `%c` parameter?

---

<sup>**[src/http.c, line 675 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/243#-JlFOXLIz1xisODSgGwl)** ([raw file](https://github.com/cesanta/fossa/blob/0660863599cb337ce8fc8a197096a278ae71abfd/src/http.c#L675)):</sup>
it falls in the category of exposing potential snippets of the SSI source, which is considered a bad thing

---

**Comment by cpq** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/243)







---

<sup>**[src/http.c, line 598 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/243#-JlFMCGxJdOAZCExOU-A)** ([raw file](https://github.com/cesanta/fossa/blob/0660863599cb337ce8fc8a197096a278ae71abfd/src/http.c#L598)):</sup>
Changed

---

<sup>**[src/http.c, line 676 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/243#-JlFOXLIz1xisODSgGwl)** ([raw file](https://github.com/cesanta/fossa/blob/0660863599cb337ce8fc8a197096a278ae71abfd/src/http.c#L676)):</sup>
Silently ignoring now.

---

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/243)

Reviewed files:
- fossa.c @ r3
- src/http.c @ r3





---

**Pull request merged**
