### PR TITLE
Rename CHANGELOG to ReleaseNotes

### PR DESCRIPTION
**Pull request by cpq**
Rename README.adoc to README.md

We reference release notes in the contracts that we sign.
All README files and ReleaseNotes files should be uniformly named and formatted across all Cesanta projects.

[Review on Reviewable](https://reviewable.io/reviews/cesanta/fossa/233)

### CODE REVIEW

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/233)



---

what's the rationale behind switching back to markdown?

I don't particularly fancy mixed case filenames. Alternatives I saw used by people:

- releasenotes.md
- RELEASENOTES.md
- release-notes.md

---

**Comment by cpq** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/233)



---

The rationale is to have all readme's and changelog files being the same across all projects.
I don't mind calling all release note files "CHANGELOG", as soon as they are the same. OK for CHANGELOG?

---

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/233)



---

RELEASENOTES or CHANGELOG it doesn't matter for me.
IMHO "release notes" is a more modern term, so perhaps we should switch to it.

 I just wonder if we should stick to adoc or switch to md ?

---

**Comment by cpq** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/233)



---

md is more widely used, so for these two files I'd use md
For other docs, adoc seems more feasible, cause it's way more flexible.
readmes and changelogs do not need flexibility.

---

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/233)

Reviewed files:
- CHANGELOG.adoc @ r1
- docs/ReleaseNotes.md @ r1
- fossa.c @ r1
- README.adoc @ r1
- README.md @ r1





---

**Pull request merged**
