### PR TITLE
Add Arduino example (restful_client/W5100)

### PR DESCRIPTION
**Pull request by alashkin**
Hi, @rojer 

Please review this PR.

In general, it contains restful_client example for W5100 and small changes to get it working.

Thanx.

[Review on Reviewable](https://reviewable.io/reviews/cesanta/fossa/270)

### CODE REVIEW

**Comment by rojer** [comment]
---

<sup>**[examples/arduino_restful_client/arduino_restful_client.ino, line 26 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/270#-JmXtYRQ8_rF2QwkLvp7)** ([raw file](https://github.com/cesanta/fossa/blob/9c6b9807e11e8da9661aedf85a8e5248bb9829e4/examples/arduino_restful_client/arduino_restful_client.ino#L26)):</sup>
THIS SHOULD BE CHANGED TOO
or it will be cargo-culted and then we'll have people wondering why two arduinos on the same network don't - or rather do, but not all the time.
mention that this HAS to be change to a proper address before going into production and HAS to be different between devices in development. giving link to http://en.wikipedia.org/wiki/MAC_address may be useful too.

---

<sup>**[examples/arduino_restful_server/arduino_restful_server.ino, line 49 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/270#-JmXtv6uR7bUal9levof)** ([raw file](https://github.com/cesanta/fossa/blob/9c6b9807e11e8da9661aedf85a8e5248bb9829e4/examples/arduino_restful_server/arduino_restful_server.ino#L49)):</sup>
same here

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/270)

**Comment by mmikulicic** [comment]
---

<sup>**[examples/arduino_restful_client/arduino_restful_client.ino, line 26 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/270#-JmXtYRQ8_rF2QwkLvp7)** ([raw file](https://github.com/cesanta/fossa/blob/9c6b9807e11e8da9661aedf85a8e5248bb9829e4/examples/arduino_restful_client/arduino_restful_client.ino#L26)):</sup>
 Doesn't the shield come with a hw Mac address? AFAIK NICs have a Mac address stored in a ROM that has to be read by the driver and written in a register during initialisation.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/270)

**Comment by rojer** [comment]
---

<sup>**[examples/arduino_restful_client/arduino_restful_client.ino, line 26 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/270#-JmXtYRQ8_rF2QwkLvp7)** ([raw file](https://github.com/cesanta/fossa/blob/9c6b9807e11e8da9661aedf85a8e5248bb9829e4/examples/arduino_restful_client/arduino_restful_client.ino#L26)):</sup>
yeah, good point. ethernet interfaces should come with properly allocated MAC already set.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/270)

**Comment by alashkin** [comment]
---

<sup>**[examples/arduino_restful_client/arduino_restful_client.ino, line 26 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/270#-JmXtYRQ8_rF2QwkLvp7)** ([raw file](https://github.com/cesanta/fossa/blob/9c6b9807e11e8da9661aedf85a8e5248bb9829e4/examples/arduino_restful_client/arduino_restful_client.ino#L26)):</sup>
It's not about W5100.
Some of them goes with sticker. Mine - not.
According forums most of people uses DEADBEEF.
W5100 datasheet offer to visit  IEEE site and obtain MAC.
And all examples go with DEADBEEF.
So, looks like the only thing I can do is adding comment, like the rest of W5100 samples
```
// assign a MAC address for the ethernet controller.
// fill in your address here:
```

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/270)

**Comment by alashkin** [comment]
---

<sup>**[examples/arduino_restful_client/arduino_restful_client.ino, line 26 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/270#-JmXtYRQ8_rF2QwkLvp7)** ([raw file](https://github.com/cesanta/fossa/blob/9c6b9807e11e8da9661aedf85a8e5248bb9829e4/examples/arduino_restful_client/arduino_restful_client.ino#L26)):</sup>
Comment added to header

---

<sup>**[examples/arduino_restful_server/arduino_restful_server.ino, line 49 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/270#-JmXtv6uR7bUal9levof)** ([raw file](https://github.com/cesanta/fossa/blob/9c6b9807e11e8da9661aedf85a8e5248bb9829e4/examples/arduino_restful_server/arduino_restful_server.ino#L49)):</sup>
Comment added to header

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/270)

**Comment by mmikulicic** [comment]
---

<sup>**[examples/arduino_restful_client/arduino_restful_client.ino, line 26 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/270#-JmXtYRQ8_rF2QwkLvp7)** ([raw file](https://github.com/cesanta/fossa/blob/9c6b9807e11e8da9661aedf85a8e5248bb9829e4/examples/arduino_restful_client/arduino_restful_client.ino#L26)):</sup>
ok, I see, lazy assess, they put it on a sticker but not on a rom!?

I understand that the W5100 chip manufacturer doesn't assign it, since their product is intended to be just a component in a solution, but the arduino ethernet shield should have added a prom on the board. If only the W5100 itself hd an few bytes eeprom on chip...

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/270)

**Comment by alashkin** [comment]
---

<sup>**[examples/arduino_restful_client/arduino_restful_client.ino, line 26 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/270#-JmXtYRQ8_rF2QwkLvp7)** ([raw file](https://github.com/cesanta/fossa/blob/9c6b9807e11e8da9661aedf85a8e5248bb9829e4/examples/arduino_restful_client/arduino_restful_client.ino#L26)):</sup>
In my case they didn't put it even on sticker :)
I'm happy with DEADBEEF.

W5100 says nothing about onboad eeprom. Only RX/TX memory (16kb)

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/270)

**Comment by mmikulicic** [comment]
---

<sup>**[examples/arduino_restful_client/arduino_restful_client.ino, line 26 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/270#-JmXtYRQ8_rF2QwkLvp7)** ([raw file](https://github.com/cesanta/fossa/blob/9c6b9807e11e8da9661aedf85a8e5248bb9829e4/examples/arduino_restful_client/arduino_restful_client.ino#L26)):</sup>
yep it's sad, but we cannot do anything better here

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/270)

**Comment by rojer** [comment]
---

<sup>**[examples/arduino_restful_client/arduino_restful_client.ino, line 26 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/270#-JmXtYRQ8_rF2QwkLvp7)** ([raw file](https://github.com/cesanta/fossa/blob/9c6b9807e11e8da9661aedf85a8e5248bb9829e4/examples/arduino_restful_client/arduino_restful_client.ino#L26)):</sup>
"everyone uses 0xdeadbeef" is exactly the problem.
move it under the "CHANGE THESE VARIABLES" section and add a comment to use MAC address from sticker if available or pick a unique locally administered address (0xDEADBEEFFEED happens to be one). put a warning in LOUD letters that devices with the same MAC must not be on the same ethernet network. stick a link to wikipedia in there.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/270)

**Comment by alashkin** [comment]
---

<sup>**[examples/arduino_restful_client/arduino_restful_client.ino, line 26 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/270#-JmXtYRQ8_rF2QwkLvp7)** ([raw file](https://github.com/cesanta/fossa/blob/9c6b9807e11e8da9661aedf85a8e5248bb9829e4/examples/arduino_restful_client/arduino_restful_client.ino#L26)):</sup>
Done.

---

<sup>**[examples/arduino_restful_server/arduino_restful_server.ino, line 49 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/270#-JmXtv6uR7bUal9levof)** ([raw file](https://github.com/cesanta/fossa/blob/9c6b9807e11e8da9661aedf85a8e5248bb9829e4/examples/arduino_restful_server/arduino_restful_server.ino#L49)):</sup>
Comments added

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/270)

**Comment by rojer** [comment]
---

<sup>**[examples/arduino_restful_client/arduino_restful_client.ino, line 34 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/270#-JmXtYRQ8_rF2QwkLvp7)** ([raw file](https://github.com/cesanta/fossa/blob/9c6b9807e11e8da9661aedf85a8e5248bb9829e4/examples/arduino_restful_client/arduino_restful_client.ino#L34)):</sup>
we're overdoing with caps, i think :) let's go with the following phrasing:
// NB: Devices with the same address must not end up on the same network.
// Use MAC address provided by device manufacturer (e.g. on a sticker).
// If there isn't one, use a random one from the locally administered range.
// See http://en.wikipedia.org/wiki/MAC_address for details.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/270)

**Comment by alashkin** [comment]
---

<sup>**[examples/arduino_restful_client/arduino_restful_client.ino, line 34 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/270#-JmXtYRQ8_rF2QwkLvp7)** ([raw file](https://github.com/cesanta/fossa/blob/9c6b9807e11e8da9661aedf85a8e5248bb9829e4/examples/arduino_restful_client/arduino_restful_client.ino#L34)):</sup>
Done.

---

<sup>**[examples/arduino_restful_server/arduino_restful_server.ino, line 56 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/270#-JmXtv6uR7bUal9levof)** ([raw file](https://github.com/cesanta/fossa/blob/9c6b9807e11e8da9661aedf85a8e5248bb9829e4/examples/arduino_restful_server/arduino_restful_server.ino#L56)):</sup>
Changed as well.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/270)

**Comment by rojer** [comment]
Reviewed files:
- examples/arduino_restful_client/arduino_restful_client.ino @ r4
- examples/arduino_restful_client/Makefile @ r1
- examples/arduino_restful_server/arduino_restful_server.ino @ r4
- examples/restful_server/restful_server.c @ r1
- fossa.c @ r1
- platforms/arduino_ethernet_W5100/avrsupport.cpp @ r1
- platforms/arduino_ethernet_W5100/avrsupport.h @ r1
- platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp @ r1
- platforms/arduino_ethernet_W5100/src/W5100_sockets.h @ r1
- platforms/arduino_wifi_CC3000/src/CC3000_utils.cpp @ r1
- platforms/arduino_wifi_CC3000/src/CC3000_utils.h @ r1
- src/net.c @ r1

---



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/270)

**Comment by alashkin** [comment]
Contribution to #199

**Pull request merged**
