### PR TITLE
Add support of CC3000 (server)

### PR DESCRIPTION
**Pull request by alashkin**
Hi, @rojer 

Please, review this PR.

It is support of CC3000 for fossa (only server - aka restful_server).
This code is based on Adafruit/Texas instruments library (https://github.com/adafruit/Adafruit_CC3000_Library)

Library stores in fossa's rep unformatted (so, sometimes code style could be strange). Later I'll make an amalgamation and use clang-format against it.

[Review on Reviewable](https://reviewable.io/reviews/cesanta/fossa/268)

### CODE REVIEW

**Comment by rojer** [comment]
i'm off today, if you want it reviewed sooner than tomorrow you may want to have someone else do it.

**Comment by mmikulicic** [comment]
I can take this. 

First a quick round of comments about some basic stuff I don't understand.

---



---

<sup>**[platforms/arduino_common/avrdebug.cpp, line 19 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/268#-JmSVLF1ItXIa1WxJ9id)** ([raw file](https://github.com/cesanta/fossa/blob/c8b5a7affbbaf9d712380a2c639e05332fbbd491/platforms/arduino_common/avrdebug.cpp#L19)):</sup>
Should we really use gcc extensions?
I know that the this is platform specific code, and it's likely that all AVR builds will be done via GCC (or clang, which will support this GNU extension) but still...

---

<sup>**[platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/socket.cpp, line 302 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/268#-JmSX5Jod7bcyBXeuZc8)** ([raw file](https://github.com/cesanta/fossa/blob/c8b5a7affbbaf9d712380a2c639e05332fbbd491/platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/socket.cpp#L302)):</sup>
what is this?

---

<sup>**[platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/socket.cpp, line 1111 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/268#-JmSYhKxCkekgU8PND2W)** ([raw file](https://github.com/cesanta/fossa/blob/c8b5a7affbbaf9d712380a2c639e05332fbbd491/platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/socket.cpp#L1111)):</sup>
what is the rationale for inserting this polls ? For example what does this particular instance here do ? If select returns an event another poll is done immediately after. 

---

<sup>**[platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/socket.h, line 426 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/268#-JmSZhGCygYQ70sJVMhK)** ([raw file](https://github.com/cesanta/fossa/blob/c8b5a7affbbaf9d712380a2c639e05332fbbd491/platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/socket.h#L426)):</sup>
can we remove this blocking gethostbyname, since fossa has it's own async DNS client ?

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/268)

**Comment by alashkin** [comment]
---

<sup>**[platforms/arduino_common/avrdebug.cpp, line 19 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/268#-JmSVLF1ItXIa1WxJ9id)** ([raw file](https://github.com/cesanta/fossa/blob/c8b5a7affbbaf9d712380a2c639e05332fbbd491/platforms/arduino_common/avrdebug.cpp#L19)):</sup>
You want to replace it with `0x80` and so on?

---

<sup>**[platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/socket.cpp, line 302 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/268#-JmSX5Jod7bcyBXeuZc8)** ([raw file](https://github.com/cesanta/fossa/blob/c8b5a7affbbaf9d712380a2c639e05332fbbd491/platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/socket.cpp#L302)):</sup>
`yield()` is a way to support cooperative multitasking on arduino.
It is recommended to call yield() from (potentially) long running loops

---

<sup>**[platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/socket.cpp, line 1111 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/268#-JmSYhKxCkekgU8PND2W)** ([raw file](https://github.com/cesanta/fossa/blob/c8b5a7affbbaf9d712380a2c639e05332fbbd491/platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/socket.cpp#L1111)):</sup>
Yes, I'll remove a couple of them. Where was extra calls between select & recv

---

<sup>**[platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/socket.h, line 426 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/268#-JmSZhGCygYQ70sJVMhK)** ([raw file](https://github.com/cesanta/fossa/blob/c8b5a7affbbaf9d712380a2c639e05332fbbd491/platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/socket.h#L426)):</sup>
Take a look to signature. it is now "usual" gethostbyname.
It is here because another parts of library use it.
Amalgamation won't contain this.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/268)

**Comment by mmikulicic** [comment]
---

<sup>**[platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/socket.cpp, line 302 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/268#-JmSX5Jod7bcyBXeuZc8)** ([raw file](https://github.com/cesanta/fossa/blob/c8b5a7affbbaf9d712380a2c639e05332fbbd491/platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/socket.cpp#L302)):</sup>
It looks that the cooperative scheduler is only implemented on the due. I understand that we should use it even if it's a nop, but on non-due arduinos this will just spin reading on the irq pin.

Isn't there a better way of waiting for events ? What is the probability of missing interrupts ? Should we poll for missing interrupts in the timer interrupt ?

---

<sup>**[platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/socket.h, line 426 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/268#-JmSZhGCygYQ70sJVMhK)** ([raw file](https://github.com/cesanta/fossa/blob/c8b5a7affbbaf9d712380a2c639e05332fbbd491/platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/socket.h#L426)):</sup>
ok

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/268)

**Comment by alashkin** [comment]
---

<sup>**[platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/socket.cpp, line 302 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/268#-JmSX5Jod7bcyBXeuZc8)** ([raw file](https://github.com/cesanta/fossa/blob/c8b5a7affbbaf9d712380a2c639e05332fbbd491/platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/socket.cpp#L302)):</sup>
I can add `delay(10)` but on mega it is just 'while(millis() < finish_time) yield()`, so - we'll get the same :)

As for this loop, it's from here:
http://e2e.ti.com/support/wireless_connectivity/f/851/p/304445/1060800

On this forum it doesn't contain `cc3k_int_pool`, but I don't see problems to keep it here. 
As for better way - not sure, coz  `hci_event_handler` started from `while (1) {`... So - loop again.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/268)

**Comment by mmikulicic** [comment]
---

<sup>**[platforms/arduino_common/avrdebug.cpp, line 19 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/268#-JmSVLF1ItXIa1WxJ9id)** ([raw file](https://github.com/cesanta/fossa/blob/c8b5a7affbbaf9d712380a2c639e05332fbbd491/platforms/arduino_common/avrdebug.cpp#L19)):</sup>
not so important, but yes ideally we should always write portable C code
(if not really required for some important feature, this is just aesthetics).
`0x80` or `(1<<7)` depending on the context both are good imho.

---

<sup>**[platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/socket.cpp, line 1111 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/268#-JmSYhKxCkekgU8PND2W)** ([raw file](https://github.com/cesanta/fossa/blob/c8b5a7affbbaf9d712380a2c639e05332fbbd491/platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/socket.cpp#L1111)):</sup>
My cargo cult detector bell is ringing, but I understand it's hard to figure out exactly where the interrupt can be lost, so I guess it's safe to poll a few times more than necessary.

Did you add these defensively or you really noticed that it gets stuck here as well sometimes?

---

<sup>**[platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/socket.cpp, line 1283 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/268#-JmSfNKVCu-dhPOqw2af)** ([raw file](https://github.com/cesanta/fossa/blob/c8b5a7affbbaf9d712380a2c639e05332fbbd491/platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/socket.cpp#L1283)):</sup>
can you explain why is this select necessary ? I don't understand it from the comment.

---

<sup>**[platforms/arduino_wifi_CC3000/src/CC3000_utils.cpp, line 38 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/268#-JmSfbhpJbl_pV3aWRxH)** ([raw file](https://github.com/cesanta/fossa/blob/c8b5a7affbbaf9d712380a2c639e05332fbbd491/platforms/arduino_wifi_CC3000/src/CC3000_utils.cpp#L38)):</sup>
what happens if there is no DHCP response, ever ?
Shouldn't we return an error after a while. Perhaps the user can provide a fallback configuration ?

Why is the DHCP mandatory here even if we have a static ip ?

---

<sup>**[platforms/arduino_wifi_CC3000/src/CC3000_utils.cpp, line 57 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/268#-JmSg5oFusFOrfUPCrXr)** ([raw file](https://github.com/cesanta/fossa/blob/c8b5a7affbbaf9d712380a2c639e05332fbbd491/platforms/arduino_wifi_CC3000/src/CC3000_utils.cpp#L57)):</sup>
why this second checkDHCP ?

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/268)

**Comment by mmikulicic** [comment]
Reviewed files:
- examples/arduino_restful_server/arduino_restful_server.ino @ r1
- platforms/arduino_common/avrdebug.cpp @ r1
- platforms/arduino_common/avrlibc_compat.h @ r1
- platforms/arduino_ethernet_W5100/src/W5100_sockets.h @ r1
- platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/Adafruit_CC3000.cpp @ r1
- platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/Adafruit_CC3000_Server.cpp @ r1
- platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/library.properties @ r1
- platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/cc3000_common.h @ r1
- platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/sntp.cpp @ r1
- platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/socket.cpp @ r1
- platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/socket.h @ r1
- platforms/arduino_wifi_CC3000/src/CC3000_utils.cpp @ r1
- platforms/arduino_wifi_CC3000/src/CC3000_utils.h @ r1

---

<sup>**[platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/socket.cpp, line 302 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/268#-JmSX5Jod7bcyBXeuZc8)** ([raw file](https://github.com/cesanta/fossa/blob/c8b5a7affbbaf9d712380a2c639e05332fbbd491/platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/socket.cpp#L302)):</sup>
I mean, this packets are getting sent somehow, by some ISR routine. Why cannot the ISR routine keep track of unsent packets and send the close HCI command when the packets are actually sent ?

Furthermore, there is something else that confuses me:
aren't `tSLInformation.NumberOfSentPackets` and `tSLInformation.NumberOfReleasedPackets` globals ?
What if there are other connections ? Does this work only because since without a scheduler the `yield` here is NOP and actually block here until the ISR actually sends out all outgoing stuff and eventually the two numbers converge ?

On the other hand I guess that on Due, we should do all networking IO from the same task, because it doesn't look that this driver is reentrant.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/268)

**Comment by alashkin** [comment]
---

<sup>**[platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/socket.cpp, line 302 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/268#-JmSX5Jod7bcyBXeuZc8)** ([raw file](https://github.com/cesanta/fossa/blob/c8b5a7affbbaf9d712380a2c639e05332fbbd491/platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/socket.cpp#L302)):</sup>
We can wait for `HCI_EVENT_CC3000_CAN_SHUT_DOWN` event, (or use cc3000bit globals - `HCI_EVENT_CC3000_CAN_SHUT_DOWN` set bit where by default). But again - it will be almost the same - globals, for all connections.
As for `yield` - yes, it could be a problem here.  So - we can freeze here or we can allow other tasks to continue. Last could be dangerous, you are right, but I still think it is better and just freeze everything.

---

<sup>**[platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/socket.cpp, line 1111 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/268#-JmSYhKxCkekgU8PND2W)** ([raw file](https://github.com/cesanta/fossa/blob/c8b5a7affbbaf9d712380a2c639e05332fbbd491/platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/socket.cpp#L1111)):</sup>
Defensively.
Code is based on adafuit's library for Arduino WiFi CC3000 shield and they call cc3k_pool befor every call to CC3000
Like this:
```
  cc3k_int_poll();
  if (netapp_timeout_values(&aucDHCP, &aucARP, &aucKeepalive, &aucInactivity) !=
      0) {
    CC3K_PRINTLN_F("Error setting inactivity timeout!");
    return;
  }
  // Create a TCP socket
  cc3k_int_poll();
  int16_t soc = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
  if (soc < 0) {
    CC3K_PRINTLN_F("Couldn't create listening socket!");
    return;
  }
  // Set the socket's accept call as non-blocking.
  cc3k_int_poll();
  char arg = SOCK_ON;  // nsd: looked in TI example code and they pass this as a
                       // 'short' in one example, and 'char' in two others.
                       // 'char' seems as likely work, and has no endianess
                       // issue
  if (cc3k_setsockopt(soc, SOL_SOCKET, SOCKOPT_ACCEPT_NONBLOCK, &arg, sizeof(arg)) <
      0) {
    CC3K_PRINTLN_F("Couldn't set socket as non-blocking!");
    return;
  }
  // Bind the socket to a TCP address.
  sockaddr_in address;
  address.sin_family = AF_INET;
  address.sin_addr.s_addr = htonl(0);  // Listen on any network interface,
                                       // equivalent to INADDR_ANY in sockets
                                       // programming.
  address.sin_port = htons(_port);     // Listen on the specified port.
  cc3k_int_poll();
  if (bind(soc, (sockaddr *) &address, sizeof(address)) < 0) {
    CC3K_PRINTLN_F("Error binding listen socket to address!");
    return;
  }
  // Start listening for connections.
  // The backlog parameter is 0 as it is not supported on TI's CC3000 firmware.
  cc3k_int_poll();
  if (listen(soc, 0) < 0) {
    CC3K_PRINTLN_F("Error opening socket for listening!");
    return;
  }
```

---

<sup>**[platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/socket.cpp, line 1283 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/268#-JmSfNKVCu-dhPOqw2af)** ([raw file](https://github.com/cesanta/fossa/blob/c8b5a7affbbaf9d712380a2c639e05332fbbd491/platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/socket.cpp#L1283)):</sup>
Look comment at line 175 (in`HostFlowControlConsumeBuff`, noted 04-06-2015 by tdicola)

---

<sup>**[platforms/arduino_wifi_CC3000/src/CC3000_utils.cpp, line 38 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/268#-JmSfbhpJbl_pV3aWRxH)** ([raw file](https://github.com/cesanta/fossa/blob/c8b5a7affbbaf9d712380a2c639e05332fbbd491/platforms/arduino_wifi_CC3000/src/CC3000_utils.cpp#L38)):</sup>
Yep, I forget to add `TODO(alashkin): add timeout`
Actually, it's a first part of PR.

>Why is the DHCP mandatory here even if we have a static ip 

User can provide all-zeroes as ip, gw, dns ans so on - and CC3000 started to work with DHCP.
And actually CC3000 tries to talk with DCHP in any case (its from support forum), and CheckDCHP() means nothing but IP was assigned - static or dynamic.

---

<sup>**[platforms/arduino_wifi_CC3000/src/CC3000_utils.cpp, line 57 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/268#-JmSg5oFusFOrfUPCrXr)** ([raw file](https://github.com/cesanta/fossa/blob/c8b5a7affbbaf9d712380a2c639e05332fbbd491/platforms/arduino_wifi_CC3000/src/CC3000_utils.cpp#L57)):</sup>
Trying to avoid CC3000 reboot on IP change. Not completed. Thinking. Can add comment about it.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/268)

**Comment by alashkin** [comment]
---

<sup>**[platforms/arduino_common/avrdebug.cpp, line 19 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/268#-JmSVLF1ItXIa1WxJ9id)** ([raw file](https://github.com/cesanta/fossa/blob/c8b5a7affbbaf9d712380a2c639e05332fbbd491/platforms/arduino_common/avrdebug.cpp#L19)):</sup>
Done.

---

<sup>**[platforms/arduino_wifi_CC3000/src/CC3000_utils.cpp, line 38 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/268#-JmSfbhpJbl_pV3aWRxH)** ([raw file](https://github.com/cesanta/fossa/blob/c8b5a7affbbaf9d712380a2c639e05332fbbd491/platforms/arduino_wifi_CC3000/src/CC3000_utils.cpp#L38)):</sup>
Timeout added.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/268)

**Comment by alashkin** [comment]
---

<sup>**[platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/socket.h, line 426 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/268#-JmSZhGCygYQ70sJVMhK)** ([raw file](https://github.com/cesanta/fossa/blob/c8b5a7affbbaf9d712380a2c639e05332fbbd491/platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/socket.h#L426)):</sup>
Done.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/268)

**Comment by alashkin** [comment]
---

<sup>**[platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/socket.cpp, line 1111 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/268#-JmSYhKxCkekgU8PND2W)** ([raw file](https://github.com/cesanta/fossa/blob/c8b5a7affbbaf9d712380a2c639e05332fbbd491/platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/socket.cpp#L1111)):</sup>
Some of `cc3k_int_poll` removed

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/268)

**Comment by mmikulicic** [comment]
Reviewed files:
- platforms/arduino_common/avrdebug.cpp @ r2
- platforms/arduino_ethernet_W5100/avrsupport.cpp @ r2
- platforms/arduino_ethernet_W5100/avrsupport.h @ r2
- platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/socket.cpp @ r2
- platforms/arduino_wifi_CC3000/src/CC3000_utils.cpp @ r2

---

<sup>**[platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/socket.cpp, line 302 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/268#-JmSX5Jod7bcyBXeuZc8)** ([raw file](https://github.com/cesanta/fossa/blob/c8b5a7affbbaf9d712380a2c639e05332fbbd491/platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/socket.cpp#L302)):</sup>
let's keep it like this and document that all network IO should be done from one task.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/268)

**Comment by mmikulicic** [comment]
LGTM

---



---



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/268)

**Comment by alashkin** [comment]
Contribution to #199

**Pull request merged**
