### PR TITLE
Add Arduino (W5100) support

### PR DESCRIPTION
**Pull request by alashkin**
Hi, @rojer 

Please, review this PR.

It implements support of Arduino Ethernet Shield (W5100) for fossa.

Note: avrsupport.h & avrsupport.cpp is just an amalgamation of avrdebug, avrlibc_compat and W5100_sockets files.

[Review on Reviewable](https://reviewable.io/reviews/cesanta/fossa/262)

### CODE REVIEW

**Comment by rojer** [comment]
why do you use .cpp? i don't see much (in fact, any) "pp" used :)

i did a quick pass over the code, but for in-depth review can you point me at the docs/sdk you're using? i have a number of questions about W5100 usage which i think can be answered by the docs.

---

Reviewed files:
- platforms/arduino_ethernet_W5100/avrsupport.cpp @ r1
- platforms/arduino_ethernet_W5100/avrsupport.h @ r1

---

<sup>**[platforms/arduino_common/avrdebug.h, line 15 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/262#-JmDAVWH9rHh_XxhZb7b)** ([raw file](https://github.com/cesanta/fossa/blob/fd523b23bb614e549fc720d5a9afa7717df2317c/platforms/arduino_common/avrdebug.h#L15)):</sup>
typo: memory

---

<sup>**[platforms/arduino_common/avrlibc_compat.h, line 14 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/262#-JmDH7P8Tyud-L0Z_6OZ)** ([raw file](https://github.com/cesanta/fossa/blob/fd523b23bb614e549fc720d5a9afa7717df2317c/platforms/arduino_common/avrlibc_compat.h#L14)):</sup>
typo: stuff

---

<sup>**[platforms/arduino_common/avrlibc_compat.h, line 36 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/262#-JmDAuLefhoeazmG8Ous)** ([raw file](https://github.com/cesanta/fossa/blob/fd523b23bb614e549fc720d5a9afa7717df2317c/platforms/arduino_common/avrlibc_compat.h#L36)):</sup>
doesn't avr libc have a function to convert to long long?

---

<sup>**[platforms/arduino_common/avrlibc_compat.h, line 44 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/262#-JmDBPl-311R61uyT8dv)** ([raw file](https://github.com/cesanta/fossa/blob/fd523b23bb614e549fc720d5a9afa7717df2317c/platforms/arduino_common/avrlibc_compat.h#L44)):</sup>
avr libc doesn't have gettimeofday? then why do we need timeval?

---

<sup>**[platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp, line 16 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/262#-JmD9QJHHt8cNrJefTbl)** ([raw file](https://github.com/cesanta/fossa/blob/fd523b23bb614e549fc720d5a9afa7717df2317c/platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp#L16)):</sup>
typo: least.

also: is there a way to tell which endianness is used?

---

<sup>**[platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp, line 72 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/262#-JmDIv5fHNkHcs_zkg7q)** ([raw file](https://github.com/cesanta/fossa/blob/fd523b23bb614e549fc720d5a9afa7717df2317c/platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp#L72)):</sup>
same point about size: don't trust user-provided size blindly, make sure it's sufficient and only copy the amount actually produced.

---

<sup>**[platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp, line 152 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/262#-JmDJP-1q9M4Dc15V4ad)** ([raw file](https://github.com/cesanta/fossa/blob/fd523b23bb614e549fc720d5a9afa7717df2317c/platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp#L152)):</sup>
this is what passes for "any available port", i guess :)
make this a top-level constant, add a note on its usage and a todo to implement properly.

---

<sup>**[platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp, line 285 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/262#-JmD952pX2hXU_wbzmBR)** ([raw file](https://github.com/cesanta/fossa/blob/fd523b23bb614e549fc720d5a9afa7717df2317c/platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp#L285)):</sup>
you should copy sizeof(int) because that's the size of the result. in fact, you should return EINVAL if *optlen != sizeof(int).

---

<sup>**[platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp, line 287 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/262#-JmD8vRd0DJjscsexiRb)** ([raw file](https://github.com/cesanta/fossa/blob/fd523b23bb614e549fc720d5a9afa7717df2317c/platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp#L287)):</sup>
0 is success, but should it be? looks like the only supported option is SO_ERROR.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/262)

**Comment by alashkin** [comment]
Coz the most of Arduino library is C++. And IDE compiles sketch using avr-g++. And SPI (I use it in the PR) library is C++ as well.. 

As for docs: there is https://www.sparkfun.com/datasheets/DevTools/Arduino/W5100_Datasheet_v1_1_6.pdf - official datasheet.
And there is non-bsd sockets implement in arduino library. On OS X with Arduino 1.6 IDE installed it is located here: Arduino ▸ Contents ▸ Resources ▸ Java ▸ libraries ▸ Ethernet ▸ src ▸ utility

---



---

<sup>**[platforms/arduino_common/avrdebug.h, line 15 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/262#-JmDAVWH9rHh_XxhZb7b)** ([raw file](https://github.com/cesanta/fossa/blob/fd523b23bb614e549fc720d5a9afa7717df2317c/platforms/arduino_common/avrdebug.h#L15)):</sup>
Done.

---

<sup>**[platforms/arduino_common/avrlibc_compat.h, line 14 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/262#-JmDH7P8Tyud-L0Z_6OZ)** ([raw file](https://github.com/cesanta/fossa/blob/fd523b23bb614e549fc720d5a9afa7717df2317c/platforms/arduino_common/avrlibc_compat.h#L14)):</sup>
Done.

---

<sup>**[platforms/arduino_common/avrlibc_compat.h, line 36 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/262#-JmDAuLefhoeazmG8Ous)** ([raw file](https://github.com/cesanta/fossa/blob/fd523b23bb614e549fc720d5a9afa7717df2317c/platforms/arduino_common/avrlibc_compat.h#L36)):</sup>
There is no avr libc =). There _are_ avr libcs. For every board could be its own libc.
DUE has rich libc (almost normal). Mega has nothing. And `stroll` is absent to.
A bit later I'll try to compile for all available boards and (maybe) add some `#ifndef`  

---

<sup>**[platforms/arduino_common/avrlibc_compat.h, line 44 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/262#-JmDBPl-311R61uyT8dv)** ([raw file](https://github.com/cesanta/fossa/blob/fd523b23bb614e549fc720d5a9afa7717df2317c/platforms/arduino_common/avrlibc_compat.h#L44)):</sup>
Socket's `select` use it.

---

<sup>**[platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp, line 16 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/262#-JmD9QJHHt8cNrJefTbl)** ([raw file](https://github.com/cesanta/fossa/blob/fd523b23bb614e549fc720d5a9afa7717df2317c/platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp#L16)):</sup>
>typo: least.

Fixed

>also: is there a way to tell which endianness is used?

As I know, all of arduinos are little-endian. But I have no idea how to get it in compile time. I didn't see any endianness related constants provided by avr-gcc

---

<sup>**[platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp, line 72 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/262#-JmDIv5fHNkHcs_zkg7q)** ([raw file](https://github.com/cesanta/fossa/blob/fd523b23bb614e549fc720d5a9afa7717df2317c/platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp#L72)):</sup>
Wdym?
srtNcpy copies only size bytes of until #0.
Buffer should be at least 16 bytes, and it's checked at the beginning of the function.

---

<sup>**[platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp, line 152 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/262#-JmDJP-1q9M4Dc15V4ad)** ([raw file](https://github.com/cesanta/fossa/blob/fd523b23bb614e549fc720d5a9afa7717df2317c/platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp#L152)):</sup>
W5100 have only 4 sockets =). Not sure, what we should add code for this thing.
But OK - fixed.

---

<sup>**[platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp, line 285 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/262#-JmD952pX2hXU_wbzmBR)** ([raw file](https://github.com/cesanta/fossa/blob/fd523b23bb614e549fc720d5a9afa7717df2317c/platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp#L285)):</sup>
It was fixed in R2, look like you looked before I repushed branch.
Fixed.

---

<sup>**[platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp, line 287 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/262#-JmD8vRd0DJjscsexiRb)** ([raw file](https://github.com/cesanta/fossa/blob/fd523b23bb614e549fc720d5a9afa7717df2317c/platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp#L287)):</sup>
The same as above.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/262)

**Comment by rojer** [comment]
i'm using linux, but ok, i think i found it.
is it the same as here https://github.com/Wiznet/WIZ_Ethernet_Library/blob/master/Arduino%20IDE%201.5.x/Ethernet/src/utility/w5100.h ?

---



---

<sup>**[platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp, line 80 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/262#-JmDIv5fHNkHcs_zkg7q)** ([raw file](https://github.com/cesanta/fossa/blob/fd523b23bb614e549fc720d5a9afa7717df2317c/platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp#L80)):</sup>
yes, you're right.

---

<sup>**[platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp, line 417 \[r2\]](https://reviewable.io:443/reviews/cesanta/fossa/262#-JmDZ2rICOHHQnfcit5A)** ([raw file](https://github.com/cesanta/fossa/blob/6dbe110e5c2ae03a17813f7569d8b5afa2b61e41/platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp#L417)):</sup>
looks like the sockets, as implemented, are async-only. i realize this is all fossa needs, but you should still make a note of it in the header.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/262)

**Comment by alashkin** [comment]
Yes, it is the same

---



---

<sup>**[platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp, line 80 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/262#-JmDIv5fHNkHcs_zkg7q)** ([raw file](https://github.com/cesanta/fossa/blob/fd523b23bb614e549fc720d5a9afa7717df2317c/platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp#L80)):</sup>
Done.

---

<sup>**[platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp, line 417 \[r2\]](https://reviewable.io:443/reviews/cesanta/fossa/262#-JmDZ2rICOHHQnfcit5A)** ([raw file](https://github.com/cesanta/fossa/blob/6dbe110e5c2ae03a17813f7569d8b5afa2b61e41/platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp#L417)):</sup>
Done.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/262)

**Comment by rojer** [comment]
---

<sup>**[platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp, line 175 \[r3\]](https://reviewable.io:443/reviews/cesanta/fossa/262#-JmDkV4jb2Lr1PlTKzIN)** ([raw file](https://github.com/cesanta/fossa/blob/6a8b8df26a0909d5ef736d440ae37b69cdf12949/platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp#L175)):</sup>
long identifier names squashed like this arenoteasilyreadable. are we running out of underscores or something? :)

also, some (most? all?) of these helpers can be made static.
or - hey, we are in .cpp here - put in an anonymous namespace.

---

<sup>**[platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp, line 188 \[r3\]](https://reviewable.io:443/reviews/cesanta/fossa/262#-JmDlr9DnWtqUhDGvHPS)** ([raw file](https://github.com/cesanta/fossa/blob/6a8b8df26a0909d5ef736d440ae37b69cdf12949/platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp#L188)):</sup>
you're not checking for ssConnecting here. why not? won't it make a "read-only" connection never complete (i.e. i call connect but never intend to write and select() for reading only - which i'm pretty sure is a valid thing to do in "big" libraries).

---

<sup>**[platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp, line 349 \[r3\]](https://reviewable.io:443/reviews/cesanta/fossa/262#-JmDmyGMnFNGVGvZ50_q)** ([raw file](https://github.com/cesanta/fossa/blob/6a8b8df26a0909d5ef736d440ae37b69cdf12949/platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp#L349)):</sup>
typo: avail_bytes

---

<sup>**[platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp, line 381 \[r3\]](https://reviewable.io:443/reviews/cesanta/fossa/262#-JmDnPFIUdYhrKcC-LxD)** ([raw file](https://github.com/cesanta/fossa/blob/6a8b8df26a0909d5ef736d440ae37b69cdf12949/platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp#L381)):</sup>
typo: avail_bytes

---

<sup>**[platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp, line 629 \[r3\]](https://reviewable.io:443/reviews/cesanta/fossa/262#-JmDo8cXg-v294Et6JDU)** ([raw file](https://github.com/cesanta/fossa/blob/6a8b8df26a0909d5ef736d440ae37b69cdf12949/platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp#L629)):</sup>
typos: connection, drops, another

---

<sup>**[platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp, line 725 \[r3\]](https://reviewable.io:443/reviews/cesanta/fossa/262#-JmDp2JRuEX4T6xBCiPl)** ([raw file](https://github.com/cesanta/fossa/blob/6a8b8df26a0909d5ef736d440ae37b69cdf12949/platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp#L725)):</sup>
will yield() sleep until next interrup/event or will this run as a tight loop?

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/262)

**Comment by alashkin** [comment]
---

<sup>**[platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp, line 175 \[r3\]](https://reviewable.io:443/reviews/cesanta/fossa/262#-JmDkV4jb2Lr1PlTKzIN)** ([raw file](https://github.com/cesanta/fossa/blob/6a8b8df26a0909d5ef736d440ae37b69cdf12949/platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp#L175)):</sup>
>put in an anonymous namespace

I was asked to avoid C++ as much as possible. 
In order to fit into 20kb it is possible to remove SPI & W5100 library and then it will be C.

Static - OK, done + renamed

---

<sup>**[platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp, line 188 \[r3\]](https://reviewable.io:443/reviews/cesanta/fossa/262#-JmDlr9DnWtqUhDGvHPS)** ([raw file](https://github.com/cesanta/fossa/blob/6a8b8df26a0909d5ef736d440ae37b69cdf12949/platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp#L188)):</sup>
Not sure.
According `select` specification  non-blocking connect become _writable_ on success.
But since I'm not sure I added `W5100_proceed_non_blocking` call

---

<sup>**[platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp, line 349 \[r3\]](https://reviewable.io:443/reviews/cesanta/fossa/262#-JmDmyGMnFNGVGvZ50_q)** ([raw file](https://github.com/cesanta/fossa/blob/6a8b8df26a0909d5ef736d440ae37b69cdf12949/platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp#L349)):</sup>
Done.

---

<sup>**[platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp, line 381 \[r3\]](https://reviewable.io:443/reviews/cesanta/fossa/262#-JmDnPFIUdYhrKcC-LxD)** ([raw file](https://github.com/cesanta/fossa/blob/6a8b8df26a0909d5ef736d440ae37b69cdf12949/platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp#L381)):</sup>
Done.

---

<sup>**[platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp, line 629 \[r3\]](https://reviewable.io:443/reviews/cesanta/fossa/262#-JmDo8cXg-v294Et6JDU)** ([raw file](https://github.com/cesanta/fossa/blob/6a8b8df26a0909d5ef736d440ae37b69cdf12949/platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp#L629)):</sup>
Done.

---

<sup>**[platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp, line 725 \[r3\]](https://reviewable.io:443/reviews/cesanta/fossa/262#-JmDp2JRuEX4T6xBCiPl)** ([raw file](https://github.com/cesanta/fossa/blob/6a8b8df26a0909d5ef736d440ae37b69cdf12949/platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp#L725)):</sup>
No, `yield()` just allows Arduino to do another tasks.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/262)

**Comment by rojer** [comment]
---

<sup>**[platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp, line 731 \[r3\]](https://reviewable.io:443/reviews/cesanta/fossa/262#-JmDp2JRuEX4T6xBCiPl)** ([raw file](https://github.com/cesanta/fossa/blob/6a8b8df26a0909d5ef736d440ae37b69cdf12949/platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp#L731)):</sup>
in that case, i think we should sleep for a configurable, non-zero by default amount of time (which can be set to zero if the user wishes to burn some cycles on polling).

---

<sup>**[platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp, line 750 \[r4\]](https://reviewable.io:443/reviews/cesanta/fossa/262#-JmE1AaYm_yV6uEl4CwU)** ([raw file](https://github.com/cesanta/fossa/blob/e84d1340a29fa8ddcddf006b8c961013c92fd701/platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp#L750)):</sup>
returning success from non-implemented functions seems wrong.

---

<sup>**[platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp, line 754 \[r4\]](https://reviewable.io:443/reviews/cesanta/fossa/262#-JmE1LiRScrrMafKdUuF)** ([raw file](https://github.com/cesanta/fossa/blob/e84d1340a29fa8ddcddf006b8c961013c92fd701/platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp#L754)):</sup>
ditto

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/262)

**Comment by alashkin** [comment]
---

<sup>**[platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp, line 731 \[r3\]](https://reviewable.io:443/reviews/cesanta/fossa/262#-JmDp2JRuEX4T6xBCiPl)** ([raw file](https://github.com/cesanta/fossa/blob/6a8b8df26a0909d5ef736d440ae37b69cdf12949/platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp#L731)):</sup>
The only "bonus" it gives is delayed response. 
If arduino has another tasks - `yield` allows to do them.
If not - let it check network. It doesn't causes overheating, coz the most of time it will ask sockets.
Also, let's take a look into `delay` library function :
```
void delay(unsigned long ms)
{
	uint16_t start = (uint16_t)micros();

	while (ms > 0) {
		yield();
		if (((uint16_t)micros() - start) >= 1000) {
			ms--;
			start += 1000;
		}
	}
}
```

If `select()` calls `delay` result will be almost the same.

---

<sup>**[platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp, line 750 \[r4\]](https://reviewable.io:443/reviews/cesanta/fossa/262#-JmE1AaYm_yV6uEl4CwU)** ([raw file](https://github.com/cesanta/fossa/blob/e84d1340a29fa8ddcddf006b8c961013c92fd701/platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp#L750)):</sup>
Fossa tries to set non-blocking mode. 
Sockets already in non-block mode - so function returns 0.
If functions returns -1 it causes error in fossa and nothing else.

---

<sup>**[platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp, line 754 \[r4\]](https://reviewable.io:443/reviews/cesanta/fossa/262#-JmE1LiRScrrMafKdUuF)** ([raw file](https://github.com/cesanta/fossa/blob/e84d1340a29fa8ddcddf006b8c961013c92fd701/platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp#L754)):</sup>
ditto.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/262)

**Comment by alashkin** [comment]
---

<sup>**[platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp, line 750 \[r4\]](https://reviewable.io:443/reviews/cesanta/fossa/262#-JmE1AaYm_yV6uEl4CwU)** ([raw file](https://github.com/cesanta/fossa/blob/e84d1340a29fa8ddcddf006b8c961013c92fd701/platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp#L750)):</sup>
The only reason why I'm not surround `fcntl` with `#ifndef __AVR__` coz I gonna introduce blocking sockets mode a bit later (for V7)

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/262)

**Comment by rojer** [comment]
---

<sup>**[platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp, line 731 \[r3\]](https://reviewable.io:443/reviews/cesanta/fossa/262#-JmDp2JRuEX4T6xBCiPl)** ([raw file](https://github.com/cesanta/fossa/blob/6a8b8df26a0909d5ef736d440ae37b69cdf12949/platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp#L731)):</sup>
ok, i give up :)

---

<sup>**[platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp, line 750 \[r4\]](https://reviewable.io:443/reviews/cesanta/fossa/262#-JmE1AaYm_yV6uEl4CwU)** ([raw file](https://github.com/cesanta/fossa/blob/e84d1340a29fa8ddcddf006b8c961013c92fd701/platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp#L750)):</sup>
i'd implement enough of both fcntl and setsockopt to make current usage by fossa possible and EINVAL everything else.
this will make failures plainly obvious if other usage is added.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/262)

**Comment by alashkin** [comment]
---

<sup>**[platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp, line 731 \[r3\]](https://reviewable.io:443/reviews/cesanta/fossa/262#-JmDp2JRuEX4T6xBCiPl)** ([raw file](https://github.com/cesanta/fossa/blob/6a8b8df26a0909d5ef736d440ae37b69cdf12949/platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp#L731)):</sup>
Done.

---

<sup>**[platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp, line 750 \[r4\]](https://reviewable.io:443/reviews/cesanta/fossa/262#-JmE1AaYm_yV6uEl4CwU)** ([raw file](https://github.com/cesanta/fossa/blob/e84d1340a29fa8ddcddf006b8c961013c92fd701/platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp#L750)):</sup>
Done.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/262)

**Comment by rojer** [comment]
---

<sup>**[platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp, line 758 \[r4\]](https://reviewable.io:443/reviews/cesanta/fossa/262#-JmE1AaYm_yV6uEl4CwU)** ([raw file](https://github.com/cesanta/fossa/blob/e84d1340a29fa8ddcddf006b8c961013c92fd701/platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp#L758)):</sup>
errno = EINVAL here and below, otherwise LGTM

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/262)

**Comment by alashkin** [comment]
---

<sup>**[platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp, line 758 \[r4\]](https://reviewable.io:443/reviews/cesanta/fossa/262#-JmE1AaYm_yV6uEl4CwU)** ([raw file](https://github.com/cesanta/fossa/blob/e84d1340a29fa8ddcddf006b8c961013c92fd701/platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp#L758)):</sup>
Done.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/262)

**Comment by rojer** [comment]
LGTM

---



---



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/262)

**Comment by alashkin** [comment]
Contribution to #199

**Pull request merged**
