### PR TITLE
Add simple URI rewriting mechanism

### PR DESCRIPTION
**Pull request by gelraen**
Configured with -b flag:
 * -b /path/ - no rewriting, pass URI as is
 * -b /path/=/otherpath/ - replace "/path/" prefix with "/otherpath/"
 * -b /path= - strip "/path" prefix from URI

Also fix -r option handling.

[Review on Reviewable](https://reviewable.io/reviews/cesanta/fossa/263)

### CODE REVIEW

**Comment by mmikulicic** [comment]
---

<sup>**[apps/load_balancer/load_balancer.c, line 125 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/263#-JmFEKxgMBM6njYmvVFu)** ([raw file](https://github.com/cesanta/fossa/blob/d89592cffb05c769bb0d6b99a8ae8e806570f3f8/apps/load_balancer/load_balancer.c#L125)):</sup>
pls put the declaration at the beginning of the block

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/263)

**Comment by gelraen** [comment]
---

<sup>**[apps/load_balancer/load_balancer.c, line 125 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/263#-JmFEKxgMBM6njYmvVFu)** ([raw file](https://github.com/cesanta/fossa/blob/d89592cffb05c769bb0d6b99a8ae8e806570f3f8/apps/load_balancer/load_balancer.c#L125)):</sup>
Done.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/263)

**Comment by cpq** [comment]
Reviewed files:
- apps/load_balancer/load_balancer.c @ r2

---

<sup>**[apps/load_balancer/load_balancer.c, line 21 \[r2\]](https://reviewable.io:443/reviews/cesanta/fossa/263#-JmFfuYGPEeGsxgIobmC)** ([raw file](https://github.com/cesanta/fossa/blob/8d5e57499d999188edbf8b8691e2096ca8797d44/apps/load_balancer/load_balancer.c#L21)):</sup>
Move this to the top of the file, and wrap into #ifndef MAX_BACKENDS 

---

<sup>**[apps/load_balancer/load_balancer.c, line 114 \[r2\]](https://reviewable.io:443/reviews/cesanta/fossa/263#-JmHhOn8DLvnuGmCZlvc)** ([raw file](https://github.com/cesanta/fossa/blob/8d5e57499d999188edbf8b8691e2096ca8797d44/apps/load_balancer/load_balancer.c#L114)):</sup>
We can do a rewrite in three large chunks: copy all data before URI, write uri replacement, write everything past the URI - all in one go.

We need to iterate through headers if we want to change/inject headers though.

---

<sup>**[apps/load_balancer/load_balancer.c, line 142 \[r2\]](https://reviewable.io:443/reviews/cesanta/fossa/263#-JmHiZeB8xLGGCqHI24K)** ([raw file](https://github.com/cesanta/fossa/blob/8d5e57499d999188edbf8b8691e2096ca8797d44/apps/load_balancer/load_balancer.c#L142)):</sup>
The logic is not entirely correct. We need to keep track of request sizes, and do rewrite when previous request got forwarded. Imagine a situation when we got 3 pipelined request in one TCP segment.  Current code will do only 1 rewrite.

Also, eliminate code duplication.

---

<sup>**[apps/load_balancer/load_balancer.c, line 217 \[r2\]](https://reviewable.io:443/reviews/cesanta/fossa/263#-JmHkzwqpDwmBrX3PDvx)** ([raw file](https://github.com/cesanta/fossa/blob/8d5e57499d999188edbf8b8691e2096ca8797d44/apps/load_balancer/load_balancer.c#L217)):</sup>
For clarity, please introduce a define, something like this:
#define URI_REWRITE_MARKER ((void *) (long) -1)

---

<sup>**[apps/load_balancer/load_balancer.c, line 253 \[r2\]](https://reviewable.io:443/reviews/cesanta/fossa/263#-JmHk4mQy949lwOocqCI)** ([raw file](https://github.com/cesanta/fossa/blob/8d5e57499d999188edbf8b8691e2096ca8797d44/apps/load_balancer/load_balancer.c#L253)):</sup>
Please add a configurable for a log file, where we'll log balancing decisions. In case of problems, we can ask people to enable logging and debug their logs.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/263)

**Comment by gelraen** [comment]
---

<sup>**[apps/load_balancer/load_balancer.c, line 142 \[r2\]](https://reviewable.io:443/reviews/cesanta/fossa/263#-JmHiZeB8xLGGCqHI24K)** ([raw file](https://github.com/cesanta/fossa/blob/8d5e57499d999188edbf8b8691e2096ca8797d44/apps/load_balancer/load_balancer.c#L142)):</sup>
Agreed. This issue existed even before: backend choice is done based on the first request and everything else is pushed as is, even though next requests might not match the uri_prefix.

Inserting "Connection: close" in replies should stop clients from pipelining requests, but will increase page load time. I'll go forward with this approach as it looks a bit simpler to implement.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/263)

**Comment by cpq** [comment]
---

<sup>**[apps/load_balancer/load_balancer.c, line 142 \[r2\]](https://reviewable.io:443/reviews/cesanta/fossa/263#-JmHiZeB8xLGGCqHI24K)** ([raw file](https://github.com/cesanta/fossa/blob/8d5e57499d999188edbf8b8691e2096ca8797d44/apps/load_balancer/load_balancer.c#L142)):</sup>
SGTM, closing the connection seems like the easiest option at the moment

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/263)

**Comment by gelraen** [comment]
PTAL

---



---

<sup>**[apps/load_balancer/load_balancer.c, line 21 \[r2\]](https://reviewable.io:443/reviews/cesanta/fossa/263#-JmFfuYGPEeGsxgIobmC)** ([raw file](https://github.com/cesanta/fossa/blob/8d5e57499d999188edbf8b8691e2096ca8797d44/apps/load_balancer/load_balancer.c#L21)):</sup>
Dropped it altogether.

---

<sup>**[apps/load_balancer/load_balancer.c, line 114 \[r2\]](https://reviewable.io:443/reviews/cesanta/fossa/263#-JmHhOn8DLvnuGmCZlvc)** ([raw file](https://github.com/cesanta/fossa/blob/8d5e57499d999188edbf8b8691e2096ca8797d44/apps/load_balancer/load_balancer.c#L114)):</sup>
Yup, done.

---

<sup>**[apps/load_balancer/load_balancer.c, line 142 \[r2\]](https://reviewable.io:443/reviews/cesanta/fossa/263#-JmHiZeB8xLGGCqHI24K)** ([raw file](https://github.com/cesanta/fossa/blob/8d5e57499d999188edbf8b8691e2096ca8797d44/apps/load_balancer/load_balancer.c#L142)):</sup>
Done.

---

<sup>**[apps/load_balancer/load_balancer.c, line 217 \[r2\]](https://reviewable.io:443/reviews/cesanta/fossa/263#-JmHkzwqpDwmBrX3PDvx)** ([raw file](https://github.com/cesanta/fossa/blob/8d5e57499d999188edbf8b8691e2096ca8797d44/apps/load_balancer/load_balancer.c#L217)):</sup>
Done.

---

<sup>**[apps/load_balancer/load_balancer.c, line 253 \[r2\]](https://reviewable.io:443/reviews/cesanta/fossa/263#-JmHk4mQy949lwOocqCI)** ([raw file](https://github.com/cesanta/fossa/blob/8d5e57499d999188edbf8b8691e2096ca8797d44/apps/load_balancer/load_balancer.c#L253)):</sup>
Done.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/263)

**Pull request merged**
