### PR TITLE
Fix portability for Arduino Mega

### PR DESCRIPTION
**Pull request by alashkin**
Hi, @mmikulicic 

Ready to run fossa on Arduino Mega?

Please, make this review of this chaotic PR. 

[Review on Reviewable](https://reviewable.io/reviews/cesanta/fossa/250)

### CODE REVIEW

**Comment by alashkin** [comment]
Sounds good.
I'll make it - when this PR will be assigned back on me :)

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/250)

Reviewed files:
- fossa.c @ r1
- fossa.h @ r1
- src/coap.c @ r1
- src/common.h @ r1
- src/dns.c @ r1
- src/http.c @ r1
- src/internal.h @ r1
- src/md5.c @ r1
- src/net.c @ r1
- src/net.h @ r1
- src/resolv.c @ r1
- src/util.c @ r1
- src/util.h @ r1





---

<sup>**[src/dns.c, line 273 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/250#-JljigW7DfQlBAr1kMPf)** ([raw file](https://github.com/cesanta/fossa/blob/3add06104a3d5a7985848267a2684b61d2802e10/src/dns.c#L273)):</sup>
Is it because `data[n]` gets promoted to (unsigned?) int ?

Below in `md5.c` you also cast `data[2] << 8`, should we do it here as well?

---

<sup>**[src/http.c, line 323 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/250#-JljjILQecfANtGLmdzU)** ([raw file](https://github.com/cesanta/fossa/blob/3add06104a3d5a7985848267a2684b61d2802e10/src/http.c#L323)):</sup>
is it because AVR doesn't support unaligned access?

---

<sup>**[src/http.c, line 985 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/250#-JljjdYf5dutGw5IH-SF)** ([raw file](https://github.com/cesanta/fossa/blob/3add06104a3d5a7985848267a2684b61d2802e10/src/http.c#L985)):</sup>
is it the same as `unsigned long` ?

---

<sup>**[src/md5.c, line 146 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/250#-JljjjUEcLKEUkj_4jeB)** ([raw file](https://github.com/cesanta/fossa/blob/3add06104a3d5a7985848267a2684b61d2802e10/src/md5.c#L146)):</sup>
shouldn't clang-format (3.6) add a space here?

---

**Comment by alashkin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/250)



---

`AVR_NOFS` replaced by `NS_DISABLE_FILESYSTEM` as well.

---

**Comment by alashkin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/250)







---

<sup>**[src/dns.c, line 273 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/250#-JljigW7DfQlBAr1kMPf)** ([raw file](https://github.com/cesanta/fossa/blob/3add06104a3d5a7985848267a2684b61d2802e10/src/dns.c#L273)):</sup>
Yes, it's because of that. It's promoted  to 16bit int and `<<16` & `<< 24` work incorrect. 
As for `md5.c` - is't oversafe =). I've removed cast where. 

---

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/250)



---

I don't see it yet, did you push it ?

---

**Comment by alashkin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/250)



---

I will reassign PR to you when all will be ready.

---

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/250)



---

One of the nicest features of reviewable is the comment batching, so you can jut publish all together when you're ready.
I opened a feature request so the current assignee can be viewed directly from reviewable.

---

**Comment by alashkin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/250)







---

<sup>**[src/http.c, line 985 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/250#-JljjdYf5dutGw5IH-SF)** ([raw file](https://github.com/cesanta/fossa/blob/3add06104a3d5a7985848267a2684b61d2802e10/src/http.c#L985)):</sup>
The same :)
I just copied type from compiler error.

---

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/250)







---

<sup>**[src/http.c, line 985 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/250#-JljjdYf5dutGw5IH-SF)** ([raw file](https://github.com/cesanta/fossa/blob/3add06104a3d5a7985848267a2684b61d2802e10/src/http.c#L985)):</sup>
let's use `unsigned long` then, for uniformity

---

**Comment by alashkin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/250)







---

<sup>**[src/md5.c, line 146 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/250#-JljjjUEcLKEUkj_4jeB)** ([raw file](https://github.com/cesanta/fossa/blob/3add06104a3d5a7985848267a2684b61d2802e10/src/md5.c#L146)):</sup>
I think should. But doesn't do.

---

**Comment by alashkin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/250)



---

PTAL

---

<sup>**[src/http.c, line 323 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/250#-JljjILQecfANtGLmdzU)** ([raw file](https://github.com/cesanta/fossa/blob/3add06104a3d5a7985848267a2684b61d2802e10/src/http.c#L323)):</sup>
Actually, some of them.
I tried with Mega - looks OK, but compiler generates warning.
But I read on SO what ARM version may produce interruption in case of unaligned access.

---

**Comment by alashkin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/250)







---

<sup>**[src/http.c, line 985 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/250#-JljjdYf5dutGw5IH-SF)** ([raw file](https://github.com/cesanta/fossa/blob/3add06104a3d5a7985848267a2684b61d2802e10/src/http.c#L985)):</sup>
Done.

---

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/250)

Reviewed files:
- fossa.c @ r2
- fossa.h @ r2
- src/common.h @ r2
- src/http.c @ r2
- src/md5.c @ r2
- src/net.c @ r2
- src/resolv.c @ r2
- src/util.c @ r2
- src/util.h @ r2





---

**Comment by alashkin** [comment]
Contribution to #199

**Pull request merged**
