### PR TITLE
Add JS sorting to directory listing

### PR DESCRIPTION
**Pull request by cpq**
Also, fix possible leak in http handler.

[Review on Reviewable](https://reviewable.io/reviews/cesanta/fossa/248)

### CODE REVIEW

**Comment by alashkin** [comment]
Could you rebase this against master?
Too much changes I've already seen

**Comment by cpq** [comment]
Rebased, and deleted stray diff commit.

**Comment by alashkin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/248)







---

<sup>**[src/http.c, line 778 \[r2\]](https://reviewable.io:443/reviews/cesanta/fossa/248#-JlcyxWqr5YasqSA3M4n)** ([raw file](https://github.com/cesanta/fossa/blob/b9af0e45329d249b2bd5785680b04647c6dd0884/src/http.c#L778)):</sup>
I still think that it is possible to kill previous transfer by invoking new one.  Is it OK?

---

**Comment by alashkin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/248)

Reviewed files:
- fossa.c @ r2
- README.md @ r2
- src/http.c @ r2
- test/unit_test.c @ r1





---

**Pull request merged**
