### PR TITLE
Add directory listing to HTTP server

### PR DESCRIPTION
**Pull request by cpq**
To test, 

Unix build:

    make -C examples/restful_server
     examples/restful_server/restful_server -d /etc

Windows build:

    wine make -C examples/restful_server restful_server.exe
    wine examples/restful_server/restful_server.exe -d /etc/

[Review on Reviewable](https://reviewable.io/reviews/cesanta/fossa/236)

### CODE REVIEW

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/236)

Reviewed files:
- examples/restful_server/Makefile @ r1
- examples/restful_server/restful_server.c @ r1
- fossa.c @ r1
- fossa.h @ r1
- src/common.h @ r1
- src/http.c @ r1
- src/http.h @ r1
- src/util.c @ r1
- src/util.h @ r1
- test/data/dir_no_index/some_file @ r1
- test/data/dir_with_index/index.html @ r1
- test/unit_test.c @ r1

---

Please rebase against master and apply `make format` (should be done for you by the pre-commit hook)

---

<sup>**[src/http.c, line 981 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/236#-JkvbtufwBCcDGKOf8IN)** ([raw file](https://github.com/cesanta/fossa/blob/852b43545a485ac959a954584fd6ca1513ca256c/src/http.c#L981)):</sup>
wouldn't just `(attrs & FILE_ATTRIBUTE_DIRECTORY) != 0` or even just `(attrs & FILE_ATTRIBUTE_DIRECTORY)` be enough ?

---

<sup>**[src/http.c, line 1036 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/236#-JkvdBQUdlU72ezXeFx9)** ([raw file](https://github.com/cesanta/fossa/blob/852b43545a485ac959a954584fd6ca1513ca256c/src/http.c#L1036)):</sup>
Please either make static or NS_INTERNAL or declare it in the headers and move it next to `ns_url_encode`.

---

<sup>**[src/http.c, line 1042 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/236#-JkvfGf80Du7fu_FKrJ9)** ([raw file](https://github.com/cesanta/fossa/blob/852b43545a485ac959a954584fd6ca1513ca256c/src/http.c#L1042)):</sup>
not clear why you need to cast to unsigned char pointer here. AFAIK both isalnum and strchr work fine with signed char.

---

<sup>**[src/http.c, line 1068 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/236#-JkvgJMsDEDAn0BIaI6n)** ([raw file](https://github.com/cesanta/fossa/blob/852b43545a485ac959a954584fd6ca1513ca256c/src/http.c#L1068)):</sup>
do you mean "... use (double) case below ..."  ?

---

<sup>**[src/http.c, line 1086 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/236#-JkvgyNNCZ3knZMZfl8Q)** ([raw file](https://github.com/cesanta/fossa/blob/852b43545a485ac959a954584fd6ca1513ca256c/src/http.c#L1086)):</sup>
shouldn't we escape the filenames in order to prevent problems if somebody calls a file like this:
`<script>alert("we are all bobby tables")</script>` ?

---

<sup>**[src/util.c, line 73 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/236#-JkviVYqUHbDxpEkUSmM)** ([raw file](https://github.com/cesanta/fossa/blob/852b43545a485ac959a954584fd6ca1513ca256c/src/util.c#L73)):</sup>
NS_INTERNAL ?

---

**Comment by cpq** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/236)



---

Done

---

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/236)

Reviewed files:
- fossa.c @ r2
- fossa.h @ r2
- src/common.h @ r2
- src/http.c @ r2
- src/http.h @ r2
- src/util.c @ r2
- src/util.h @ r2
- test/unit_test.c @ r2





---

**Comment by cpq** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/236)







---

<sup>**[src/http.c, line 981 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/236#-JkvbtufwBCcDGKOf8IN)** ([raw file](https://github.com/cesanta/fossa/blob/852b43545a485ac959a954584fd6ca1513ca256c/src/http.c#L981)):</sup>
It would.
Done.

---

<sup>**[src/http.c, line 1036 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/236#-JkvdBQUdlU72ezXeFx9)** ([raw file](https://github.com/cesanta/fossa/blob/852b43545a485ac959a954584fd6ca1513ca256c/src/http.c#L1036)):</sup>
Done.

---

<sup>**[src/http.c, line 1042 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/236#-JkvfGf80Du7fu_FKrJ9)** ([raw file](https://github.com/cesanta/fossa/blob/852b43545a485ac959a954584fd6ca1513ca256c/src/http.c#L1042)):</sup>
http://stackoverflow.com/questions/11623978/why-do-ctype-functions-take-int-but-want-unsigned-char-eof

Depends how C lib implements `is*` ctype macros:

    int _CtypeBits[257] = { ... };
    #define isalpha(c)  (_Ctype_bits[(c)+1]&_ALPHA);

if an index is signed char, and < -1, then the lookup will return an undefined value.

---

<sup>**[src/http.c, line 1068 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/236#-JkvgJMsDEDAn0BIaI6n)** ([raw file](https://github.com/cesanta/fossa/blob/852b43545a485ac959a954584fd6ca1513ca256c/src/http.c#L1068)):</sup>
Yes, good catch
Fixed

---

<sup>**[src/http.c, line 1086 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/236#-JkvgyNNCZ3knZMZfl8Q)** ([raw file](https://github.com/cesanta/fossa/blob/852b43545a485ac959a954584fd6ca1513ca256c/src/http.c#L1086)):</sup>
We should. Fixed.

---

<sup>**[src/util.c, line 73 \[r1\]](https://reviewable.io:443/reviews/cesanta/fossa/236#-JkviVYqUHbDxpEkUSmM)** ([raw file](https://github.com/cesanta/fossa/blob/852b43545a485ac959a954584fd6ca1513ca256c/src/util.c#L73)):</sup>
Done.

---

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/236)

Reviewed files:
- fossa.c @ r3
- fossa.h @ r3
- src/http.c @ r3
- src/internal.h @ r3
- src/util.c @ r3





---

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/fossa/236)

Reviewed files:
- src/util.h @ r3
- test/unit_test.c @ r3





---

**Pull request merged**
